require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EstimationsController do

  # This should return the minimal set of attributes required to create a valid
  # Estimation. As you add validations to Estimation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EstimationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all estimations as @estimations" do
      estimation = Estimation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:estimations).should eq([estimation])
    end
  end

  describe "GET show" do
    it "assigns the requested estimation as @estimation" do
      estimation = Estimation.create! valid_attributes
      get :show, {:id => estimation.to_param}, valid_session
      assigns(:estimation).should eq(estimation)
    end
  end

  describe "GET new" do
    it "assigns a new estimation as @estimation" do
      get :new, {}, valid_session
      assigns(:estimation).should be_a_new(Estimation)
    end
  end

  describe "GET edit" do
    it "assigns the requested estimation as @estimation" do
      estimation = Estimation.create! valid_attributes
      get :edit, {:id => estimation.to_param}, valid_session
      assigns(:estimation).should eq(estimation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Estimation" do
        expect {
          post :create, {:estimation => valid_attributes}, valid_session
        }.to change(Estimation, :count).by(1)
      end

      it "assigns a newly created estimation as @estimation" do
        post :create, {:estimation => valid_attributes}, valid_session
        assigns(:estimation).should be_a(Estimation)
        assigns(:estimation).should be_persisted
      end

      it "redirects to the created estimation" do
        post :create, {:estimation => valid_attributes}, valid_session
        response.should redirect_to(Estimation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved estimation as @estimation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Estimation.any_instance.stub(:save).and_return(false)
        post :create, {:estimation => {}}, valid_session
        assigns(:estimation).should be_a_new(Estimation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Estimation.any_instance.stub(:save).and_return(false)
        post :create, {:estimation => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested estimation" do
        estimation = Estimation.create! valid_attributes
        # Assuming there are no other estimations in the database, this
        # specifies that the Estimation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Estimation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => estimation.to_param, :estimation => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested estimation as @estimation" do
        estimation = Estimation.create! valid_attributes
        put :update, {:id => estimation.to_param, :estimation => valid_attributes}, valid_session
        assigns(:estimation).should eq(estimation)
      end

      it "redirects to the estimation" do
        estimation = Estimation.create! valid_attributes
        put :update, {:id => estimation.to_param, :estimation => valid_attributes}, valid_session
        response.should redirect_to(estimation)
      end
    end

    describe "with invalid params" do
      it "assigns the estimation as @estimation" do
        estimation = Estimation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Estimation.any_instance.stub(:save).and_return(false)
        put :update, {:id => estimation.to_param, :estimation => {}}, valid_session
        assigns(:estimation).should eq(estimation)
      end

      it "re-renders the 'edit' template" do
        estimation = Estimation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Estimation.any_instance.stub(:save).and_return(false)
        put :update, {:id => estimation.to_param, :estimation => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested estimation" do
      estimation = Estimation.create! valid_attributes
      expect {
        delete :destroy, {:id => estimation.to_param}, valid_session
      }.to change(Estimation, :count).by(-1)
    end

    it "redirects to the estimations list" do
      estimation = Estimation.create! valid_attributes
      delete :destroy, {:id => estimation.to_param}, valid_session
      response.should redirect_to(estimations_url)
    end
  end

end
